/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntrenamientoRouteImport } from './routes/entrenamiento'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as TesoroRouteImport } from './routes/tesoro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrenamientoRoute = EntrenamientoRouteImport.update({
  id: '/entrenamiento',
  path: '/entrenamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const TesoroRoute = TesoroRouteImport.update({
  id: '/tesoro',
  path: '/tesoro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrenamiento': typeof EntrenamientoRoute
  '/mapa': typeof MapaRoute
  '/tesoro': typeof TesoroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrenamiento': typeof EntrenamientoRoute
  '/mapa': typeof MapaRoute
  '/tesoro': typeof TesoroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entrenamiento': typeof EntrenamientoRoute
  '/mapa': typeof MapaRoute
  '/tesoro': typeof TesoroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entrenamiento' | '/mapa' | '/tesoro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entrenamiento' | '/mapa' | '/tesoro'
  id: '__root__' | '/' | '/entrenamiento' | '/mapa' | '/tesoro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntrenamientoRoute: typeof EntrenamientoRoute
  MapaRoute: typeof MapaRoute
  TesoroRoute: typeof TesoroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrenamiento': {
      id: '/entrenamiento'
      path: '/entrenamiento'
      fullPath: '/entrenamiento'
      preLoaderRoute: typeof EntrenamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesoro': {
      id: '/tesoro'
      path: '/tesoro'
      fullPath: '/tesoro'
      preLoaderRoute: typeof TesoroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntrenamientoRoute: EntrenamientoRoute,
  MapaRoute: MapaRoute,
  TesoroRoute: TesoroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
