/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BarcoRouteImport } from './routes/barco'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as ReyRouteImport } from './routes/rey'
import { Route as TesoroRouteImport } from './routes/tesoro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarcoRoute = BarcoRouteImport.update({
  id: '/barco',
  path: '/barco',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const ReyRoute = ReyRouteImport.update({
  id: '/rey',
  path: '/rey',
  getParentRoute: () => rootRouteImport,
} as any)
const TesoroRoute = TesoroRouteImport.update({
  id: '/tesoro',
  path: '/tesoro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barco': typeof BarcoRoute
  '/mapa': typeof MapaRoute
  '/rey': typeof ReyRoute
  '/tesoro': typeof TesoroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barco': typeof BarcoRoute
  '/mapa': typeof MapaRoute
  '/rey': typeof ReyRoute
  '/tesoro': typeof TesoroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barco': typeof BarcoRoute
  '/mapa': typeof MapaRoute
  '/rey': typeof ReyRoute
  '/tesoro': typeof TesoroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/barco' | '/mapa' | '/rey' | '/tesoro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/barco' | '/mapa' | '/rey' | '/tesoro'
  id: '__root__' | '/' | '/barco' | '/mapa' | '/rey' | '/tesoro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarcoRoute: typeof BarcoRoute
  MapaRoute: typeof MapaRoute
  ReyRoute: typeof ReyRoute
  TesoroRoute: typeof TesoroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barco': {
      id: '/barco'
      path: '/barco'
      fullPath: '/barco'
      preLoaderRoute: typeof BarcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rey': {
      id: '/rey'
      path: '/rey'
      fullPath: '/rey'
      preLoaderRoute: typeof ReyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesoro': {
      id: '/tesoro'
      path: '/tesoro'
      fullPath: '/tesoro'
      preLoaderRoute: typeof TesoroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarcoRoute: BarcoRoute,
  MapaRoute: MapaRoute,
  ReyRoute: ReyRoute,
  TesoroRoute: TesoroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
